# Generated by Django 5.0.1 on 2024-01-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_post_slug"),
        ("tags", "0002_alter_tag_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="posts", to="tags.tag"),
        ),
    ]
